#pragma once

// Minimal table-driven runner shared by the behavioral contract tests.
// Paths to compiled shaders and glslc depfiles come from the header generated by
// tests/CMakeLists.txt (iridium_test_support).

#include "IridiumTestPaths.h"

#include <chrono>
#include <exception>
#include <filesystem>
#include <iostream>
#include <span>
#include <string>

#define IRIDIUM_CHECK(condition) \
    do { \
        if (!(condition)) { \
            std::cerr << "  check failed: " #condition " (" << __FILE__ << ':' \
                << __LINE__ << ")\n"; \
            return false; \
        } \
    } while (false)

// Like IRIDIUM_CHECK, with a streamed context message (shader name, pass, ...).
#define IRIDIUM_CHECK_MSG(condition, message) \
    do { \
        if (!(condition)) { \
            std::cerr << "  check failed: " #condition " [" << message << "] (" \
                << __FILE__ << ':' << __LINE__ << ")\n"; \
            return false; \
        } \
    } while (false)

namespace Iridium::Test {

    struct TestCase {
        const char* name;
        bool (*run)();
    };

    [[nodiscard]] inline std::filesystem::path shaderBinaryDirectory() {
        return std::filesystem::path(IRIDIUM_TEST_SHADER_BINARY_DIR);
    }
    [[nodiscard]] inline std::filesystem::path shaderDepfileDirectory() {
        return std::filesystem::path(IRIDIUM_TEST_SHADER_DEPFILE_DIR);
    }
    [[nodiscard]] inline std::filesystem::path shaderBinary(const std::string& spvName) {
        return shaderBinaryDirectory() / spvName;
    }
    // Test-only kernels compiled from tests/shaders into the build tree.
    [[nodiscard]] inline std::filesystem::path parityShader(const std::string& spvName) {
        return std::filesystem::path(IRIDIUM_TEST_PARITY_SHADER_DIR) / spvName;
    }
    [[nodiscard]] inline std::span<const char* const> compiledShaders() noexcept {
        return kIridiumCompiledShaders;
    }

    inline int runTests(std::span<const TestCase> tests) {
        size_t failures = 0;
        for (const TestCase& test : tests) {
            const auto start = std::chrono::steady_clock::now();
            bool passed = false;
            try {
                passed = test.run();
            } catch (const std::exception& exception) {
                std::cerr << "  exception: " << exception.what() << '\n';
            }
            const double milliseconds = std::chrono::duration<double, std::milli>(
                std::chrono::steady_clock::now() - start).count();
            if (passed) {
                std::cout << "[PASS] " << test.name << " (" << milliseconds << " ms)\n";
            } else {
                ++failures;
                std::cerr << "[FAIL] " << test.name << '\n';
            }
        }
        std::cout << tests.size() - failures << '/' << tests.size() << " tests passed\n";
        return failures == 0 ? 0 : 1;
    }

} // namespace Iridium::Test
