# Shared helpers for module, tool and test targets.

# --- Precompiled headers ----------------------------------------------------------
#
# A PCH force-includes its headers ahead of every translation unit of the target,
# so a header may only be listed if no translation unit depends on a macro defined
# *before* that header is first included. In particular,
# GLM_FORCE_DEPTH_ZERO_TO_ONE is defined by app/Application.h and
# editor/ViewportPicking.h ahead of their GLM includes; translation units that
# include those headers first must not receive <glm/glm.hpp> from a PCH (use
# NO_GLM or SKIP_PRECOMPILE_HEADERS). <Windows.h> is never listed for the same
# reason (NOMINMAX / WIN32_LEAN_AND_MEAN are defined per file).
#
# Engine modules (ENGINE) get no PCH in Release by default: MSVC makes different
# inlining decisions when the standard headers arrive through a force-included PCH
# (for example, std::basic_string's destructor inlines _Tidy_deallocate instead of
# tail-calling it), so Release engine code would no longer be byte-identical to
# the pre-PCH build. Debug and the test/tool translation units always use PCH.
option(IRIDIUM_ENGINE_PCH_IN_RELEASE
        "Use precompiled headers for engine modules in Release (changes MSVC inlining decisions)"
        OFF)

set(IRIDIUM_PCH_STD_HEADERS
        algorithm array atomic cmath cstddef cstdint cstring filesystem functional
        limits map memory mutex optional span string string_view unordered_map
        unordered_set utility variant vector)

# _iridium_pch_header(<out_var> <name> [GLM] [JSON] [VULKAN])
# Writes <build>/pch/<name>.h (only when its content changes) and returns its path.
function(_iridium_pch_header out_var name)
    cmake_parse_arguments(ARG "GLM;JSON;VULKAN" "" "" ${ARGN})
    set(_content "// Generated by cmake/IridiumHelpers.cmake. Do not edit.\n#pragma once\n")
    foreach(_h IN LISTS IRIDIUM_PCH_STD_HEADERS)
        string(APPEND _content "#include <${_h}>\n")
    endforeach()
    if(ARG_GLM)
        string(APPEND _content "#include <glm/glm.hpp>\n")
    endif()
    if(ARG_JSON)
        string(APPEND _content "#include <nlohmann/json.hpp>\n")
    endif()
    if(ARG_VULKAN)
        string(APPEND _content "#include <vulkan/vulkan.h>\n")
    endif()
    set(_path "${CMAKE_BINARY_DIR}/pch/${name}.h")
    file(CONFIGURE OUTPUT "${_path}" CONTENT "${_content}" @ONLY)
    set(${out_var} "${_path}" PARENT_SCOPE)
endfunction()

# Shared PCH provider. Targets whose compile options and definitions match the
# provider reuse its PCH instead of building their own; every module, tool and test
# target sees the same directory-level definitions (PROJECT_ROOT_DIR, WIN32, ...)
# and flags.
_iridium_pch_header(IRIDIUM_PCH_DEFAULT_HEADER iridium_pch GLM JSON)
set(_iridium_pch_source "${CMAKE_BINARY_DIR}/pch/iridium_pch.cpp")
file(CONFIGURE OUTPUT "${_iridium_pch_source}"
        CONTENT "// PCH provider translation unit (generated).\n" @ONLY)
add_library(iridium_pch STATIC "${_iridium_pch_source}")
target_link_libraries(iridium_pch PRIVATE glm::glm nlohmann_json::nlohmann_json)
target_precompile_headers(iridium_pch PRIVATE "${IRIDIUM_PCH_DEFAULT_HEADER}")
unset(_iridium_pch_source)

get_property(IRIDIUM_MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)

# iridium_target_pch(<target> [ENGINE] [VULKAN] [NO_GLM])
#   Default: reuse the shared std+glm+json PCH.
#   ENGINE:  the target is linked into IridiumEngine: no PCH in Release (see above).
#   VULKAN:  own PCH that also contains <vulkan/vulkan.h>.
#   NO_GLM:  own PCH without GLM (targets whose translation units define
#            GLM_FORCE_* before their first GLM include).
function(iridium_target_pch target)
    cmake_parse_arguments(ARG "ENGINE;VULKAN;NO_GLM" "" "" ${ARGN})
    set(_release_guard FALSE)
    if(ARG_ENGINE AND NOT IRIDIUM_ENGINE_PCH_IN_RELEASE)
        if(NOT IRIDIUM_MULTI_CONFIG)
            if(CMAKE_BUILD_TYPE STREQUAL "Release")
                return()
            endif()
        else()
            # Multi-config generators cannot REUSE_FROM per configuration: give
            # the target its own PCH and drop it for Release.
            set(_release_guard TRUE)
        endif()
    endif()
    if(NOT ARG_VULKAN AND NOT ARG_NO_GLM AND NOT _release_guard)
        target_precompile_headers(${target} REUSE_FROM iridium_pch)
        return()
    endif()
    set(_variant JSON)
    if(NOT ARG_NO_GLM)
        list(APPEND _variant GLM)
    endif()
    if(ARG_VULKAN)
        list(APPEND _variant VULKAN)
    endif()
    _iridium_pch_header(_header ${target}_pch ${_variant})
    if(_release_guard)
        set(_header "$<$<NOT:$<CONFIG:Release>>:${_header}>")
    endif()
    target_precompile_headers(${target} PRIVATE "${_header}")
endfunction()

# --- Vendor code -------------------------------------------------------------------
# Third-party sources are compiled once, without PCH, with warnings disabled.
function(iridium_vendor_library target)
    add_library(${target} STATIC ${ARGN})
    if(MSVC)
        target_compile_options(${target} PRIVATE /w)
    else()
        target_compile_options(${target} PRIVATE -w)
    endif()
endfunction()

# --- Allocation tracking -----------------------------------------------------------
# CpuAllocationProfile.cpp replaces the global operator new/delete. It is an OBJECT
# library so its object file is linked directly into each executable that opts in
# (static-library members are only pulled in when referenced).
function(iridium_link_allocation_profile target)
    target_link_libraries(${target} PRIVATE iridium_allocation_profile)
endfunction()

# --- Executables -------------------------------------------------------------------

# iridium_add_executable(<name> SOURCES ... [LIBS ...] [ALLOCATION_PROFILE] [NO_PCH]
#                        [BENCHMARK_INFO | BENCHMARK_SOURCE_INFO])
#   Tools and tests always link iridium_core (the src include root and GLM) and
#   reuse the shared PCH unless NO_PCH is given.
#   ALLOCATION_PROFILE links the operator new/delete replacement.
#   BENCHMARK_INFO adds IRIDIUM_BENCHMARK_CONFIGURATION/COMPILER; BENCHMARK_SOURCE_INFO
#   additionally adds the configure-time commit and dirty flag.
function(iridium_add_executable name)
    cmake_parse_arguments(ARG "ALLOCATION_PROFILE;NO_PCH;BENCHMARK_INFO;BENCHMARK_SOURCE_INFO"
            "" "SOURCES;LIBS" ${ARGN})
    add_executable(${name} ${ARG_SOURCES})
    target_link_libraries(${name} PRIVATE iridium_core ${ARG_LIBS})
    if(ARG_ALLOCATION_PROFILE)
        iridium_link_allocation_profile(${name})
    endif()
    if(ARG_BENCHMARK_INFO OR ARG_BENCHMARK_SOURCE_INFO)
        target_compile_definitions(${name} PRIVATE
                IRIDIUM_BENCHMARK_CONFIGURATION="$<CONFIG>"
                IRIDIUM_BENCHMARK_COMPILER="${IRIDIUM_COMPILER_ID}")
    endif()
    if(ARG_BENCHMARK_SOURCE_INFO)
        target_compile_definitions(${name} PRIVATE
                IRIDIUM_BENCHMARK_SOURCE_COMMIT="${IRIDIUM_SOURCE_COMMIT}"
                IRIDIUM_BENCHMARK_SOURCE_DIRTY=${IRIDIUM_SOURCE_DIRTY_AT_CONFIGURE})
    endif()
    if(NOT ARG_NO_PCH)
        iridium_target_pch(${name})
    endif()
endfunction()

# iridium_add_test(<name> SOURCES ... [LIBS ...] [LABELS ...] [...iridium_add_executable options])
#   Builds the executable and registers a ctest of the same name. Labels default
#   to "unit". Tests run from the top-level build directory, as before the
#   per-module layout.
function(iridium_add_test name)
    cmake_parse_arguments(ARG "" "" "LABELS" ${ARGN})
    iridium_add_executable(${name} ${ARG_UNPARSED_ARGUMENTS})
    add_test(NAME ${name} COMMAND ${name} WORKING_DIRECTORY ${CMAKE_BINARY_DIR})
    if(NOT ARG_LABELS)
        set(ARG_LABELS unit)
    endif()
    set_tests_properties(${name} PROPERTIES LABELS "${ARG_LABELS}")
endfunction()
